# Generated by Django 2.0.2 on 2018-02-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_time']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='data_time',
            new_name='date_time',
        ),
    ]
